package catalog

import (
	"os"
	"path/filepath"
	"testing"
)

// The real file is CRLF with a [section] per model, because gen-catalog.py
// writes it for Win32's GetPrivateProfileString. Both properties are pinned
// here: a parser that only handles LF would read every value with a trailing
// \r and every URL it built would 404.
const sample = "; GENERATED by installer/gen-catalog.py -- do not edit by hand.\r\n" +
	"\r\n[catalog]\r\ncount=3\r\nmax_index=3\r\n" +
	"\r\n[recommend]\r\nrungs=2\r\nrung1_vram=16\r\nrung1_pick=3\r\ncpu_only=2\r\ndefault=2\r\n" +
	"\r\n[1]\r\ndisplay=Gemma 4 E4B IT\r\nrepo=bartowski/google_gemma-4-E4B-it-GGUF\r\n" +
	"file=google_gemma-4-E4B-it-Q4_K_M.gguf\r\nsize_gb=5.4\r\nmin_vram=6\r\nctx=32768\r\nkv=f16\r\n" +
	"\r\n[2]\r\ndisplay=Llama 3.2 3B Instruct\r\nrepo=bartowski/Llama-3.2-3B-Instruct-GGUF\r\n" +
	"file=Llama-3.2-3B-Instruct-Q8_0.gguf\r\nsize_gb=3.4\r\nmin_vram=4\r\nctx=32768\r\nkv=f16\r\n" +
	"\r\n[3]\r\ndisplay=Big One\r\nrepo=someone/Big-GGUF\r\nfile=Big-Q6_K.gguf\r\n" +
	"size_gb=18.2\r\nmin_vram=16\r\nctx=16384\r\nkv=q8_0\r\n"

func write(t *testing.T, body string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "models.ini")
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestLoadParsesCRLFCatalogue(t *testing.T) {
	c, err := Load(write(t, sample))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(c.Entries) != 3 {
		t.Fatalf("entries: got %d, want 3", len(c.Entries))
	}
	// Sorted by index, not by map iteration order.
	if c.Entries[0].Index != 1 || c.Entries[2].Index != 3 {
		t.Errorf("entries are not sorted by index: %v", c.Entries)
	}
	e := c.Entries[1]
	if e.Display != "Llama 3.2 3B Instruct" {
		t.Errorf("display: got %q", e.Display)
	}
	if e.File != "Llama-3.2-3B-Instruct-Q8_0.gguf" {
		t.Errorf("file carries stray whitespace or \\r: %q", e.File)
	}
	if e.SizeGB != 3.4 || e.MinVRAM != 4 || e.Ctx != 32768 || e.KV != "f16" {
		t.Errorf("numeric fields wrong: %+v", e)
	}
	if c.Default != 2 || c.CPUOnly != 2 {
		t.Errorf("recommend table: default=%d cpu_only=%d, want 2/2", c.Default, c.CPUOnly)
	}
}

func TestURLsAreBuiltFromRepoAndFile(t *testing.T) {
	c, err := Load(write(t, sample))
	if err != nil {
		t.Fatal(err)
	}
	e, ok := c.Find(2)
	if !ok {
		t.Fatal("entry 2 missing")
	}
	wantDL := "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q8_0.gguf"
	if got := e.DownloadURL(); got != wantDL {
		t.Errorf("DownloadURL:\n got  %s\n want %s", got, wantDL)
	}
	// /raw/ rather than /resolve/ — this is the LFS pointer the checksum comes
	// from, and fetching /resolve/ here would download the whole model instead.
	wantPtr := "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/raw/main/Llama-3.2-3B-Instruct-Q8_0.gguf"
	if got := e.PointerURL(); got != wantPtr {
		t.Errorf("PointerURL:\n got  %s\n want %s", got, wantPtr)
	}
}

func TestSectionsWithoutRepoOrFileAreNotModels(t *testing.T) {
	body := sample + "\r\n[4]\r\ndisplay=Placeholder\r\nsize_gb=1.0\r\n"
	c, err := Load(write(t, body))
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := c.Find(4); ok {
		t.Error("an entry with no repo/file was offered as a downloadable model")
	}
}

// A recommend table pointing at an index that no longer exists must not leave
// the UI with nothing preselected — it falls back to the smallest model, which
// is the safest thing to be wrong about.
func TestMissingRecommendationFallsBackToSmallest(t *testing.T) {
	body := "[recommend]\r\ncpu_only=99\r\ndefault=99\r\n" +
		"\r\n[1]\r\ndisplay=Big\r\nrepo=a/b\r\nfile=big.gguf\r\nsize_gb=18.0\r\n" +
		"\r\n[2]\r\ndisplay=Small\r\nrepo=a/c\r\nfile=small.gguf\r\nsize_gb=2.0\r\n"
	c, err := Load(write(t, body))
	if err != nil {
		t.Fatal(err)
	}
	if c.Default != 2 || c.CPUOnly != 2 {
		t.Errorf("fallback: default=%d cpu_only=%d, want the smallest (2)", c.Default, c.CPUOnly)
	}
}

func TestEmptyCatalogueIsAnError(t *testing.T) {
	if _, err := Load(write(t, "[catalog]\r\ncount=0\r\n")); err == nil {
		t.Error("a catalogue with no models should be an error, not an empty list")
	}
}

func TestMissingFileIsAnError(t *testing.T) {
	if _, err := Load(filepath.Join(t.TempDir(), "nope.ini")); err == nil {
		t.Error("a missing catalogue should be an error")
	}
}

// The real shipped file must parse. This is what catches gen-catalog.py
// changing shape without the reader being updated.
func TestRealCatalogueParses(t *testing.T) {
	p := "../../installer/models.ini"
	if _, err := os.Stat(p); err != nil {
		t.Skip("installer/models.ini not present")
	}
	c, err := Load(p)
	if err != nil {
		t.Fatalf("the shipped catalogue does not parse: %v", err)
	}
	if len(c.Entries) < 5 {
		t.Errorf("shipped catalogue has only %d entries", len(c.Entries))
	}
	for _, e := range c.Entries {
		if e.Repo == "" || e.File == "" || e.SizeGB <= 0 {
			t.Errorf("entry %d is incomplete: %+v", e.Index, e)
		}
	}
	if _, ok := c.Find(c.CPUOnly); !ok {
		t.Errorf("cpu_only points at %d, which is not in the catalogue", c.CPUOnly)
	}
}
