package mock

import (
	"fmt"
	"strings"
	"time"
)

// GenerateMarkdownReport produces a verification run report in Markdown format with proof artifacts.
func GenerateMarkdownReport(res *RunResult, story Story) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Story Verification Report: %s\n\n", story.Name))
	sb.WriteString(fmt.Sprintf("- **Story ID:** `%s`\n", story.ID))
	sb.WriteString(fmt.Sprintf("- **Run ID:** `%s`\n", res.RunID))
	sb.WriteString(fmt.Sprintf("- **Status:** **%s**\n", strings.ToUpper(res.Status)))
	sb.WriteString(fmt.Sprintf("- **Started:** %s\n", res.StartedAt.Format(time.RFC3339)))
	sb.WriteString(fmt.Sprintf("- **Duration:** %v\n", res.Duration))
	if story.Description != "" {
		sb.WriteString(fmt.Sprintf("- **Description:** %s\n", story.Description))
	}
	sb.WriteString("\n---\n\n## Step-by-Step Verification\n\n")

	for i, step := range story.Steps {
		var stepRes *StepResult
		for _, sr := range res.StepResults {
			if sr.StepIndex == step.StepIndex {
				stepRes = &sr
				break
			}
		}

		passedStatus := "❌ FAILED"
		if stepRes != nil && stepRes.Passed {
			passedStatus = "✅ PASSED"
		}

		sb.WriteString(fmt.Sprintf("### Step %d: (%s)\n\n", i+1, passedStatus))
		sb.WriteString(fmt.Sprintf("**User Prompt:**\n> %s\n\n", strings.ReplaceAll(step.Prompt, "\n", "\n> ")))

		if stepRes != nil {
			sb.WriteString(fmt.Sprintf("**Assistant Output:**\n```\n%s\n```\n\n", stepRes.Output))
			sb.WriteString(fmt.Sprintf("**Execution Time:** %v\n\n", stepRes.Duration))

			if len(stepRes.Errors) > 0 {
				sb.WriteString("**Failures / Errors:**\n")
				for _, err := range stepRes.Errors {
					sb.WriteString(fmt.Sprintf("- ⚠️ %s\n", err))
				}
				sb.WriteString("\n")
			}

			if stepRes.ImageProof != "" {
				sb.WriteString(fmt.Sprintf("**Visual Proof:**\n![Step %d Screenshot](%s)\n\n", step.StepIndex, stepRes.ImageProof))
			}
		}

		if len(step.ExpectedText) > 0 {
			sb.WriteString("**Text Assertions:**\n")
			for _, ea := range step.ExpectedText {
				sb.WriteString(fmt.Sprintf("- Expected substring: `%s`\n", ea))
			}
			sb.WriteString("\n")
		}

		if len(step.VisualAssertions) > 0 {
			sb.WriteString("**Visual Assertions:**\n")
			for _, va := range step.VisualAssertions {
				sb.WriteString(fmt.Sprintf("- %s\n", va))
			}
			sb.WriteString("\n")
		}

		if step.VisionPrompt != "" {
			sb.WriteString(fmt.Sprintf("**Vision Model Criteria:** `%s`\n\n", step.VisionPrompt))
		}
	}

	sb.WriteString("---\n*Generated by GobboNet Replay & Verification Engine*\n")
	return sb.String()
}
